"""User birthdate

Revision ID: 06416f8696df
Revises: b516dcef2621
Create Date: 2023-12-05 05:54:49.777703

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06416f8696df'
down_revision: Union[str, None] = 'b516dcef2621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
