"""Archived wishes

Revision ID: 1382cce781a5
Revises: d1b81d6f6b8b
Create Date: 2023-12-15 19:03:36.784518

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1382cce781a5'
down_revision: Union[str, None] = 'd1b81d6f6b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'wish',
        sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'is_archived')
    # ### end Alembic commands ###
