"""firebase push token saved at

Revision ID: 1dbf0fc5d054
Revises: 99f073496ee4
Create Date: 2024-10-17 20:47:31.544343

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1dbf0fc5d054'
down_revision: Union[str, None] = '99f073496ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('firebase_push_token_saved_at', sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('firebase_push_token_saved_at')

    # ### end Alembic commands ###
