"""User.firebase_push_token

Revision ID: 3b4b85568cc0
Revises: edb1cfb5e669
Create Date: 2023-11-24 18:54:34.755718

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b4b85568cc0'
down_revision: Union[str, None] = 'edb1cfb5e669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('firebase_push_token', sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firebase_push_token')
    # ### end Alembic commands ###
