"""Wish reservation

Revision ID: 704004b8dd8a
Revises: 5e0f90c5ef9e
Create Date: 2023-11-29 18:39:47.528427

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '704004b8dd8a'
down_revision: Union[str, None] = '5e0f90c5ef9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_CONSTRAINT_NAME = 'wish_reserved_by_fk'
CHECK_CONSTRAINT_NAME = 'wish_user_not_equal_reserved_by'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish') as batch_op:
        batch_op.add_column(sa.Column('reserved_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            FK_CONSTRAINT_NAME, 'user', ['reserved_by_id'], ['id']
        )
        batch_op.create_check_constraint(
            CHECK_CONSTRAINT_NAME, 'user_id <> reserved_by_id'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish') as batch_op:
        batch_op.drop_constraint(CHECK_CONSTRAINT_NAME)
        batch_op.drop_constraint(FK_CONSTRAINT_NAME, type_='foreignkey')
        batch_op.drop_column('reserved_by_id')
    # ### end Alembic commands ###
