"""User vk_access_token

Revision ID: 78d8787d056f
Revises: 28a00d13a644
Create Date: 2023-11-20 22:21:13.113927

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78d8787d056f'
down_revision: Union[str, None] = '28a00d13a644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CONSTRAINT_NAME = 'vk_access_token_unique'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(
            sa.Column('vk_access_token', sa.String(length=100), nullable=False)
        )
        batch_op.create_unique_constraint(CONSTRAINT_NAME, ['vk_access_token'])
        batch_op.drop_column('access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(
            sa.Column('access_token', sa.VARCHAR(length=100), nullable=False)
        )
        batch_op.drop_constraint(CONSTRAINT_NAME, type_='unique')
        batch_op.drop_column('vk_access_token')
    # ### end Alembic commands ###
