"""PushSendingLog model

Revision ID: 99f073496ee4
Revises: 283921af6d7a
Create Date: 2024-04-16 20:18:16.102725

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99f073496ee4'
down_revision: Union[str, None] = '283921af6d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'push_sending_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.Column('reason_user_id', sa.Uuid(), nullable=False),
        sa.Column('target_user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'reason',
            sa.Enum('CURRENT_USER_BIRTHDAY', 'FOLLOWER_BIRTHDAY', name='pushreason'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['reason_user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_sending_log')
    # ### end Alembic commands ###
