"""Wish image

Revision ID: b516dcef2621
Revises: 3a27af32987e
Create Date: 2023-12-03 20:59:48.373483

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b516dcef2621'
down_revision: Union[str, None] = '3a27af32987e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish', sa.Column('image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'image')
    # ### end Alembic commands ###
