"""pre bday push sent dt

Revision ID: cfbc250f41ae
Revises: 1dbf0fc5d054
Create Date: 2024-10-17 22:45:10.881584

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cfbc250f41ae'
down_revision: Union[str, None] = '1dbf0fc5d054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'pre_bday_push_for_followers_last_sent_at', sa.DateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pre_bday_push_for_followers_last_sent_at')

    # ### end Alembic commands ###
