"""User firebase_uid

Revision ID: edb1cfb5e669
Revises: 78d8787d056f
Create Date: 2023-11-24 00:12:47.182359

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'edb1cfb5e669'
down_revision: Union[str, None] = '78d8787d056f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CONSTRAINT_NAME = 'firebase_uid_unique'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(
            sa.Column('firebase_uid', sa.String(length=100), nullable=True)
        )
        batch_op.create_unique_constraint(CONSTRAINT_NAME, ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint(CONSTRAINT_NAME, type_='unique')
        batch_op.drop_column('firebase_uid')
    # ### end Alembic commands ###
