"""Nullable vk fields

Revision ID: f2485a629978
Revises: fb8012d5d9e5
Create Date: 2023-11-25 08:59:25.026668

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f2485a629978'
down_revision: Union[str, None] = 'fb8012d5d9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'vk_id', existing_type=sa.VARCHAR(length=15), nullable=True
        )
        batch_op.alter_column(
            'vk_access_token', existing_type=sa.VARCHAR(length=100), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'vk_access_token', existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            'vk_id', existing_type=sa.VARCHAR(length=15), nullable=False
        )
    # ### end Alembic commands ###
