"""Nullable first last name phone

Revision ID: fb8012d5d9e5
Revises: 9c47a1a8e65a
Create Date: 2023-11-25 08:56:51.248404

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb8012d5d9e5'
down_revision: Union[str, None] = '9c47a1a8e65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'first_name', existing_type=sa.VARCHAR(length=30), nullable=True
        )
        batch_op.alter_column(
            'last_name', existing_type=sa.VARCHAR(length=30), nullable=True
        )
        batch_op.alter_column(
            'phone', existing_type=sa.VARCHAR(length=15), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'phone', existing_type=sa.VARCHAR(length=15), nullable=False
        )
        batch_op.alter_column(
            'last_name', existing_type=sa.VARCHAR(length=30), nullable=False
        )
        batch_op.alter_column(
            'first_name', existing_type=sa.VARCHAR(length=30), nullable=False
        )
    # ### end Alembic commands ###
