"""Nullable vk_access_token

Revision ID: 403c03a04c9e
Revises: 3555be18e5c4
Create Date: 2023-12-16 21:21:18.156738

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '403c03a04c9e'
down_revision: Union[str, None] = '3555be18e5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'vk_access_token', existing_type=sa.VARCHAR(length=500), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'vk_access_token', existing_type=sa.VARCHAR(length=500), nullable=False
        )
    # ### end Alembic commands ###
