"""User.email nullable

Revision ID: e22f857de4f6
Revises: 22f90244e570
Create Date: 2024-01-17 21:08:38.650785

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e22f857de4f6'
down_revision: Union[str, None] = '22f90244e570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(length=100), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column(
            'email', existing_type=sa.VARCHAR(length=100), nullable=False
        )
    # ### end Alembic commands ###
